### ISSUE TITLE
Snap app crashes if upgraded in the background

### ISSUE THREAD

**Issue by bast1aan** [snapcrafters/signal-desktop#14] opened 2019-12-05 16:42 UTC
-- Copy of bug report on https://github.com/signalapp/Signal-Desktop/issues/3793 --

* [X] I have searched open and closed issues for duplicates
  

---

### Bug Description

The Signal Desktop Snap app in Ubuntu 18.04 crashes after a running for a while with following error message:

```
Unhandled Error

Error: EACCES: permission denied, rename '/home/bwelmers/snap/signal-desktop/219/.config/Signal/logs/log.log.1' -> '/home/bwelmers/snap/signal-desktop/219/.config/Signal/logs/log.log.2'
```
When looking in the list of Signal snap versions:
```
/dev/loop7                              98M   98M     0 100% /snap/signal-desktop/219
/dev/loop10                             98M   98M     0 100% /snap/signal-desktop/235
```
it looks like the snap is upgraded in the background and somehow the running instance of Signal does not handle this correctly and keeps trying to use the older config directory.

### Steps to Reproduce

Unfortunately not easy, but something like this

1.  install signal-desktop snap app and launch it, login to it, use it etc
2.  let it run until a new version is installed by snapd
3.  wait until the log needs to be rotated. Looks like that is done on daily basis.

Actual Result:

Crash

Expected Result:

Should not crash.

### Screenshots

![Screenshot_20191205_170501](https://user-images.githubusercontent.com/6011270/70253985-961fa680-1784-11ea-977d-5c7aeebdab13.png)

### Platform Info

Signal Version:

```$ snap list signal-desktop
Name            Version  Rev  Tracking  Publisher     Notes
signal-desktop  1.29.0   235  stable    snapcrafters  -
```
Operating System:

Ubuntu 18.04

Linked Device Version:

Android: Signal  4.49.18

### Link to Debug Log

https://debuglogs.org/604b3bb6f1cc01244899b902643643d3503981433d3377526d5f671b96b89c12

**Comment by popey** [comment] 2020-04-01 14:18
We have an experimental feature, designed to mitigate this issue. It's blogged about at https://ubuntu.com/blog/experimental-feature-snap-refresh-awareness-and-update-inhibition
This issue is indeed a snap-related one, and we're working to get that feature landed by default as soon as we can. For now, this is the workaround.

`snap set core experimental.refresh-app-awareness=true`

This will prevent the app updating while it's running.

**Closed by popey** 2020-04-01 14:18 UTC

**Comment by johnmee** [comment] 2021-06-28 10:14
Forgive my naivety, but could this be fixed with a "snap layout"?

https://snapcraft.io/docs/snap-layouts

**Comment by diddledan** [comment] 2021-06-28 10:37
no, snap layouts are completely orthogonal to this issue

**Comment by galgalesh** [comment] 2021-06-29 19:04
Note: duplicate of https://github.com/snapcrafters/signal-desktop/issues/8
