### ISSUE TITLE
After restarting to update the app, recent messages have disappeared from all conversation histories and they all say "chat session refreshed"

### ISSUE THREAD

**Issue by blkeller** [snapcrafters/signal-desktop#57] opened 2021-06-29 18:48 UTC
**I filed an issue for this over at the upstream repository, but the Signal folks indicated that this was likely a Snap-specific problem, so I'm refiling it here and linking to the original.**

### Original upstream bug report:
https://github.com/signalapp/Signal-Desktop/issues/5364

### Bug Description

The last two times I've updated Signal Desktop to the latest version, the application appears to have lost data after restarting the app.  Everything works fine and all conversations are perfectly in sync with my Android device before the upgrade, but after I quit and restart the application on the updated version, it's as if the internal state of Signal Desktop was thrown back in time: messages from the last several hours (both incoming and outgoing) that used to be there have disappeared from conversation histories.  The "Note to Self" conversation immediately shows "Chat session refreshed" and any individual or group conversations where I send a new message from my phone will instantly show "Chat session refreshed" on the desktop app after I send the message from my phone.  After each of my conversations has gone through the "Chat session refreshed" process, everything seems to work again without any problems going forward until the next application update.

The most recent update I did where this problem occurred was going from version 5.3.0 to 5.6.1.

### Steps to Reproduce

1.  Exit Signal Desktop (the old version) via the menu bar: File -> Quit Signal
2.  Just to be sure, wait about one minute or so to make sure the application has fully quit, and verify that the OS does not list any "signal-desktop" running processes
3.  Launch Signal Desktop again from the system's application menu.  The new version of Signal will start (having already been downloaded and staged in the background by `snapd`, waiting for the next application restart).
4. Observe the behavior described above where recent messages have disappeared and chat sessions need to be refreshed

Actual Result:

Please see details listed in "Bug Description".

Expected Result:

Signal Desktop starts up normally after an upgrade, and all messages that it had previously successfully received should still be present.  Also, there should not be a need to refresh every single chat session.

### Screenshots

![image](https://user-images.githubusercontent.com/17344566/123333115-f4e37700-d506-11eb-92bc-b95fc95a9617.png)

### Platform Info

Signal Version:

In the middle of upgrading from 5.3.0 to 5.6.1, though this has happened at least once before when upgrading from an earlier version (5.0.0 maybe?) to 5.3.0.

Operating System:

Ubuntu 16.04 running KDE Plasma desktop

Linked Device Version:

Signal 5.13.8 on Android 10

### Link to Debug Log

Signal Desktop:
https://debuglogs.org/03cb6bab920b0a7dffae3704bee9e58399a22a312a214dbac947323a171b8977.gz

Linked device Signal for Android:
https://debuglogs.org/1877d35f6e86ed4d0ad6756648f6acbafed2e067f64d29b2ecb5cb6d9efbebe2

**Comment by galgalesh** [comment] 2021-06-29 19:08
Thanks for the report, this is a duplicate of https://github.com/snapcrafters/signal-desktop/issues/8

snapd should not be upgrading Signal while it is running. Fixing this issue is being worked on. For the moment, you can enable an experimental fix for this issue by running the following command

```
snap set core experimental.refresh-app-awareness=true
```

This will prevent the app updating while it's running. For more information, see [Experimental feature: snap refresh awareness and update inhibition](https://ubuntu.com/blog/experimental-feature-snap-refresh-awareness-and-update-inhibition).

If this bug still persists after turning on refresh app awareness, then please let us know here.

**Closed by galgalesh** 2021-06-29 19:08 UTC

**Comment by blkeller** [comment] 2021-06-29 20:12
@galgalesh Thank you for the workaround.  I have turned on Refresh App Awareness, and we'll see how that goes the next time Signal updates.

I read the blog post you linked, plus [the associated bug report on Launchpad](https://bugs.launchpad.net/snapd/+bug/1616650), and it sounds like I had a fundamental misunderstanding of how the snap update process works.  I had assumed that updates were staged in the background, and that the new version only became the active version once all instances of the application were closed, then at the next launch, user data would be copied into the new context and the new version would run.  It's clear from reading those that this isn't the case and that the new version of the application files are switched into place even if the old version of the application is still running.  It sounds like the experimental option actually changes this process to better match my original assumptions, though to be honest I'm completely baffled that this isn't the default behavior.  I can see how it wouldn't matter for a CLI utility that only runs for short periods on demand, but for a long-running GUI app with a database, the default behavior seems like a recipe for disaster.

Suggestion: please consider adding information and instructions for turning on Refresh App Awareness to the Signal Desktop application's description in the Snap Store.  Since the Signal snap is essentially a user data-loss situation waiting to happen (on next update) with the default settings, I think a warning and steps to implement the workaround written right in the snap's description would help prevent the problem for new users and increase visibility of this experimental fix.

**Comment by galgalesh** [comment] 2021-06-29 20:59
> It sounds like the experimental option actually changes this process to better match my original assumptions

Indeed. Note that if, after 7 days, signal-desktop hasn't closed, the update will still happen in the background.

> to be honest I'm completely baffled that this isn't the default behavior. I can see how it wouldn't matter for a CLI utility that only runs for short periods on demand, but for a long-running GUI app with a database, the default behavior seems like a recipe for disaster.

The default behaviour indeed creates issues in multiple applications. Although the solution is a complex one because, for example, the user needs to be notified of scheduled updates so that they can restart the application in time. The developers are also wary of introducing Windows 10-style "fuck you and your workflow" forced updates.

> Suggestion: please consider adding information and instructions for turning on Refresh App Awareness to the Signal Desktop application's description in the Snap Store. Since the Signal snap is essentially a user data-loss situation waiting to happen (on next update) with the default settings, 

Good suggestion, I'll add this. I personally haven't encountered data loss with this snap before, but given the number of bugs created about this, it's clear it happens often.
