### ISSUE TITLE
"Error handling incoming message" after each update or reopen of the app

### ISSUE THREAD

**Issue by 54sledgehammer45** [snapcrafters/signal-desktop#40] opened 2020-08-07 07:27 UTC
```
$ snap list signal-desktop
Name            Version  Rev  Tracking       Publisher     Notes
signal-desktop  1.34.5   327  latest/stable  snapcrafters  -
```

For a while now, whenever I close the app, receive a few messages and then reopen it, I get a deluge of "Error handling incoming message". 
![image](https://user-images.githubusercontent.com/62136678/89620372-d8f3ca00-d88f-11ea-8630-d3b948c53fe0.png)

Most of the time resetting the session helps, but often, it's just simpler to disconnect and reconnect. This seems only to happen on the snap package. The `.deb` doesn't have this problem. I'm not sure how the app works, but I'm guessing somewhere, the state isn't saved and when restarting, it can't rebuild the key chain for the double ratchet algorithm to work.

**Comment by eduardo-jf** [comment] 2021-02-25 17:18
Just happened again. Session reset for each person on a group did the trick.
```
Name               Version                     Rev    Tracking       Publisher     Notes
signal-desktop     1.40.1                      351    latest/stable  snapcrafters```

**Comment by galgalesh** [comment] 2021-06-14 16:36
Does this happen every time, or only sometimes? It might be caused by the app updating while it is running.

Can you try running the following command and seeing if it keeps happening?

```bash
snap set core experimental.refresh-app-awareness=true
```

This will disable updates while the app is running.

More information here: https://snapcraft.io/blog/experimental-feature-snap-refresh-awareness-and-update-inhibition

**Comment by galgalesh** [comment] 2022-09-02 22:41
Closing this issue as it appears the issue hasn't happened in a long time. Let me know if this is still happening.

**Closed by galgalesh** 2022-09-02 22:41 UTC
Labels: bug
