### ISSUE TITLE
[Bug]: signal-desktop doesn't start, TypeError: Invalid Version: 6.5.10-200.fc38.x86_64 at new SemVer

### ISSUE THREAD

**Issue by UnkindPartition** [snapcrafters/signal-desktop#202] opened 2023-11-23 10:28 UTC
### What happened?

When launched, signal-desktop only shows the "Something went wrong!" screen.

### What should have happened?

It should start successfully.

### Output of `snap info $snap_name`

```shell
name:      signal-desktop
summary:   Speak Freely - Private Messenger
publisher: Snapcrafters✪
store-url: https://snapcraft.io/signal-desktop
contact:   https://github.com//snapcrafters/signal-desktop/issues
license:   unset
description: |
  **Note: To use the Signal desktop app, you must first install Signal on your phone.**
  
  Millions of people use Signal every day for free and instantaneous communication anywhere in the
  world. Send and receive high-fidelity messages, participate in HD voice/video calls, and explore a
  growing set of new features that help you stay connected. Signal's advanced privacy-preserving
  technology is always enabled, so you can focus on sharing the moments that matter with the people
  who matter to you.
  
  - Say anything - State-of-the-art end-to-end encryption (powered by the open source Signal
  Protocol™) keeps your conversations secure. Privacy isn't an optional mode; it's just the way that
  Signal works. Every message, every call, every time.
  - Go fast - Messages are delivered quickly and reliably, even on slow networks. Signal is
  optimized to operate in the most constrained environment possible.
  - Feel free - Signal is a completely independent 501c3 nonprofit. Development is supported by
  users like you. No advertisements. No trackers. No kidding.
  - Be yourself - You can use your existing phone number and address book to securely communicate
  with your friends.
  - Speak up - Whether they live across town or across the ocean, Signal's enhanced audio and video
  quality will make your friends and family feel closer.
  - Whisper in the shadows - Switch to the dark theme if you refuse to see the light.
  
  **Are you having issues?**
  
  Let us know by creating a new issue here: https://github.com/snapcrafters/signal-desktop/issues
  
  **Authors**
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - signal-desktop
snap-id:      r4LxMVp7zWramXsJQAKdamxy6TAWlaDD
tracking:     latest/stable
refresh-date: today at 12:10 EET
channels:
  latest/stable:    1.11.0 2023-11-23  (35) 137MB -
  latest/candidate: 6.39.1 2023-11-23 (556) 181MB -
  latest/beta:      ↑                             
  latest/edge:      ↑                             
installed:          1.11.0             (35) 137MB -
```

### Output of `snap connections $snap_name`

```shell
Interface        Plug                            Slot              Notes
browser-support  signal-desktop:browser-support  :browser-support  -
desktop          signal-desktop:desktop          :desktop          -
desktop-legacy   signal-desktop:desktop-legacy   :desktop-legacy   -
gsettings        signal-desktop:gsettings        :gsettings        -
home             signal-desktop:home             :home             -
network          signal-desktop:network          :network          -
opengl           signal-desktop:opengl           :opengl           -
pulseaudio       signal-desktop:pulseaudio       :pulseaudio       -
unity7           signal-desktop:unity7           :unity7           -
x11              signal-desktop:x11              :x11              -
```

### Output of `snap version`

```shell
snap    2.58.3-1.fc38
snapd   2.58.3-1.fc38
series  16
fedora  38
kernel  6.5.10-200.fc38.x86_64
```

### Teminal output of app

```shell
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "pk-gtk-module"
NODE_ENV production
NODE_CONFIG_DIR /snap/signal-desktop/35/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
Set Windows Application User Model ID (AUMID) { appUserModelId: 'org.whispersystems.signal-desktop' }
userData: /home/roman/snap/signal-desktop/35/.config/Signal
making app single instance
Fontconfig warning: "/etc/fonts/conf.d/10-sub-pixel-rgb-for-kde.conf", line 4: unknown element "description"
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"app ready","time":"2023-11-23T10:27:27.539Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"Ensure attachments directory exists","time":"2023-11-23T10:27:27.545Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"Initializing BrowserWindow config: {\"show\":true,\"width\":1920,\"height\":1011,\"minWidth\":640,\"minHeight\":360,\"autoHideMenuBar\":false,\"webPreferences\":{\"nodeIntegration\":false,\"preload\":\"/snap/signal-desktop/35/resources/app.asar/preload.js\"},\"icon\":\"/snap/signal-desktop/35/resources/app.asar/images/icon_256.png\",\"maximized\":true,\"x\":0,\"y\":69}","time":"2023-11-23T10:27:27.547Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"Detected Linux. Using default en_US spell check dictionary","time":"2023-11-23T10:27:28.438Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"pre-main prep time: 2 ms","time":"2023-11-23T10:27:28.599Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"Build expires:  2018-08-12T23:57:11.000Z","time":"2023-11-23T10:27:28.620Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"background page reloaded","time":"2023-11-23T10:27:28.639Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"environment: production","time":"2023-11-23T10:27:28.639Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"Start IndexedDB migrations","time":"2023-11-23T10:27:28.639Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"Run migrations on database with attachment data","time":"2023-11-23T10:27:28.640Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"Database status {\"firstMigrationVersion\":12,\"lastMigrationVersion\":18,\"databaseVersion\":18,\"isAlreadyUpgraded\":true}","time":"2023-11-23T10:27:28.674Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"Storage fetch","time":"2023-11-23T10:27:28.675Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"ConversationController: starting initial fetch","time":"2023-11-23T10:27:28.690Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"ConversationController: done with initial fetch","time":"2023-11-23T10:27:28.691Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"listening for registration events","time":"2023-11-23T10:27:28.691Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"opening provisioning socket https://textsecure-service.whispersystems.org","time":"2023-11-23T10:27:28.795Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"provisioning socket closed 1006","time":"2023-11-23T10:27:28.831Z","v":0}
{"name":"log","hostname":"lars","pid":13502,"level":30,"msg":"provisioning failed Error: websocket closed\n    at W3CWebSocket.socket.onclose (file://[REDACTED]/app.asar/js/libtextsecure.js:38094:22)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] ([REDACTED]/app.asar/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onConnectFailed ([REDACTED]/app.asar/node_modules/websocket/lib/W3CWebSocket.js:219:14)\n    at WebSocketClient.<anonymous> ([REDACTED]/app.asar/node_modules/websocket/lib/W3CWebSocket.js:59:25)\n    at emitOne (events.js:115:13)\n    at WebSocketClient.emit (events.js:210:7)\n    at ClientRequest.handleRequestError ([REDACTED]/app.asar/node_modules/websocket/lib/WebSocketClient.js:215:14)\n    at emitOne (events.js:115:13)\n    at ClientRequest.emit (events.js:210:7)\n    at TLSSocket.socketErrorListener (_http_client.js:401:9)","time":"2023-11-23T10:27:28.835Z","v":0}
```

**Comment by UnkindPartition** [comment] 2023-11-23 10:29
This looks similar to https://github.com/signalapp/Signal-Desktop/issues/2396, except that one is old and fixed, and this one is new. Reporting here instead of the upstream following their policy.

**Comment by UnkindPartition** [comment] 2023-11-23 10:54
Also, the same version of signal-desktop (6.39.1) installed via flatpak doesn't have this issue.

**Comment by gtopsis** [comment] 2023-11-23 12:13
Checking what is the latest **stable** version of the app in the [snapcraft](https://snapcraft.io/signal-desktop), I see that currently the version is 1.11.0, although the channel **candidate** offers the 6.39.1!
An incoming update in the morning reverted my app to the older 1.11, and I had to re-install it from the channel **candidate** in order to get a working version of the signal-desktop.

**Comment by popey** [comment] 2023-11-23 12:50
Duplicate of #203

**Closed as completed by popey** 2023-11-23 12:50 UTC
Labels: bug
