### ISSUE TITLE
[Enhancement]: Store attachements in common folder instead of individually for each snap version

### ISSUE THREAD

**Issue by s-gurevich** [snapcrafters/signal-desktop#271] opened 2024-02-23 16:45 UTC
### What changes would you like?

Snap stores multiple versions of the app on the Linux machine.
Currently, each version has its own `.config -> Signal -> attachments.noindex` folder with the attachments.
Attachments can take up a significant amount of disc space. There is probably also no real advantage or having multiple copies of the attachments.
It would be helpful to move the attachments to common folder and have only one copy.

**Comment by lengau** [comment] 2024-04-04 02:23
This is a duplicate of #112; please feel free to join the discussion there.

**Closed as not planned** 2024-04-04 02:26 UTC
Labels: enhancement
