### ISSUE TITLE
Can't Click URLs in Signal

### ISSUE THREAD

**Issue by banduccm** [snapcrafters/signal-desktop#25] opened 2020-04-12 16:16 UTC
I'm running the Signal snap (v 1.32.3) on Fedora 32 / Gnome 3.36.1.

When someone sends me a link via Signal, the link is formatted correctly and the mouse cursor changes to indicate the link is clickable, but when I click nothing happens. I have Firefox set as my default handler in Gnome settings.

I'm open to this being a config issue on my end, but googling hasn't led me to an answer yet.
If there's any logging/debug info I can provide, please let me know!

**Comment by galgalesh** [comment] 2021-06-14 17:08
I cannot reproduce this on Fedora 34. I'm closing this issue for now. Please let us know if this is still happening so we can reopen the issue and investigate further.

**Closed by galgalesh** 2021-06-14 17:08 UTC
