### ISSUE TITLE
1.33.3 snap displays all UI chars/fonts as 'boxes'

### ISSUE THREAD

**Issue by pgnd** [snapcrafters/signal-desktop#28] opened 2020-04-25 17:58 UTC
I've installed snap on openSUSE
```
snap version
	snap           2.43.3-lp151.1.1
	snapd          2.43.3-lp151.1.1
	series         16
	opensuse-leap  15.1
	kernel         5.6.6-24.gc11f000-default
```

I've installed signal-desktop via snap,
```
	snap info signal-desktop
		name:      signal-desktop
		summary:   Signal Private Messenger for Windows, Mac, and Linux
		publisher: Snapcrafters
		store-url: https://snapcraft.io/signal-desktop
		contact:   https://github.com/snapcrafters/signal-desktop/issues
		license:   unset
		description: |
		...
		commands:
		  - signal-desktop
		snap-id:      r4LxMVp7zWramXsJQAKdamxy6TAWlaDD
		tracking:     latest/stable
		refresh-date: yesterday at 12:02 PDT
		channels:
		  stable:    1.33.3 2020-04-24 (311) 111MB -
		  candidate: ↑
		  beta:      1.33.3 2020-04-24 (311) 111MB -
		  edge:      1.33.3 2020-04-24 (311) 111MB -
		installed:   1.33.3            (311) 111MB -
```

On signal-desktop launch, no apparent error.

I'm able to connect / interatct with Signal on several Android phones.

If I try to DL an item from signal-desktop, e.g., an image, to desktop, the save file dialog
displays ALL characters/fonts 'boxes',

	https://i.imgur.com/0MjIzTT.png

rebuilding local system's font-caches, per

	https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/32

has no effect; dialog^ still shows all chars as 'boxes'.

**Comment by s4wyerg** [comment] 2020-04-27 20:25
+1 same version, same error on Fedora 31

**Comment by flexiondotorg** [comment] 2020-05-18 22:26
Duplicate of #20

**Closed by flexiondotorg** 2020-05-18 22:26 UTC
